### ISSUE TITLE
[bug] Unable to install through official channels

### ISSUE THREAD

**Issue by wwjCMP** [nhannht/obsidian-historica#1]

**Comment by nhannht** [comment]
Sorry, I still not fully understand. Can you screenshot your error here?.

But I can guess the reason, 6 hours ago I updated to version 0.0.8, but the release still in draft form, the official store should not mark that version as latest release.

**Comment by nhannht** [comment]
Well, what I thought is correct. The plugins store tracking the "latest" release version through the number in manifest.json in the repository. So I edited it as version 0.0.6 (stable) and the plugin store shows 0.0.6 as the latest release. Now you can download it as normal from the store because that version was already public. 

If things still go wrong, please reopen this issue, and include your screenshot of the bug. Thank you.
