### ISSUE TITLE
Cannot update or install on Windows 10 with Obsidian 1.6.7

### ISSUE THREAD

**Issue by merlinuwe** [nhannht/obsidian-historica#15]
Cannot update or install on Windows 10 with Obsidian 1.6.7

Here are my settings:

SYSTEM INFO:
	Obsidian version: v1.6.7
	Installer version: v1.6.7
	Operating system: Windows 10 Home 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: off
	Base theme: dark
	Community theme: MagicUser v20.8.2
	Snippets enabled: 58
	Restricted mode: off
	Plugins installed: 196
	Plugins enabled: 75

**Comment by nhannht** [comment]
Thank you for report. Please wait me to check this, I have dual boot my LinuxBox with Windows (for playing games). I will answer you later (I am currently using Linux when give this reply.).

**Comment by merlinuwe** [comment]
Same issue on Android 11.

**Comment by nhannht** [comment]
Hum, I think the problem is that I accidently change the version to 0.3.0 in `manifest.json` file and push the commit to the online repository in Github (which was differented with version in the latest release  - v0.2.5 ) , Obsidian plugin store will check that file via http request and checked if both versions was the same and if they are not the same, it will trigger problem. Because I don't publish any new version yet, I think it maybe only the posible problem. 

I have already the version in manifest.json. And the install work normally in Linux with a temporary vault, sorry I still not switch to Windows to play game.

**Comment by nhannht** [comment]
If no one answer, I will expect that you can install it normally. :heart:  you

**Comment by merlinuwe** [comment]
Thanks for your engagement, I can install your plugin now at least on windows 10 and it works. ;-)

On android 11 I can install it, but I cannot activate it: "Failed to load plugin historica". (The activation button switches back.)
